# Generated by Django 5.0.1 on 2024-01-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
