# Generated by Django 4.1.13 on 2024-01-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedro',
        ),
    ]
