# Generated by Django 4.1.13 on 2024-01-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_delete_pedro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descricao',
        ),
    ]
